const { Router } = require("express");
const validate = require("../middleware/validate");
const validateParam = require("../middleware/validateParam");
const requireAdmin = require("../middleware/requireAdmin");
const requirePermission = require("../middleware/requirePermission");
const { sensitiveRateLimit } = require("../middleware/rateLimit");
const controller = require("../controllers/return.controller");
const { z } = require("zod");
const listSchema=z.object({page:z.coerce.number().int().min(1).default(1),limit:z.coerce.number().int().min(1).max(100).default(20),status:z.enum(["requested","approved","rejected","pickup-scheduled","received","refunded","replacement-initiated","completed","cancelled"]).optional(),search:z.string().trim().max(100).optional()});
const actionSchema=z.object({note:z.string().trim().max(500).optional(),reason:z.string().trim().max(500).optional(),amount:z.coerce.number().positive().optional()});
const router=Router();
router.use(requireAdmin);
router.get("/",validate(listSchema,"query"),controller.list);
router.get("/:id",validateParam("id"),controller.getById);
router.post("/:id/approve",sensitiveRateLimit,validateParam("id"),requirePermission("orders.write"),validate(actionSchema),controller.approve);
router.post("/:id/reject",sensitiveRateLimit,validateParam("id"),requirePermission("orders.write"),validate(actionSchema),controller.reject);
router.post("/:id/pickup-scheduled",sensitiveRateLimit,validateParam("id"),requirePermission("orders.write"),validate(actionSchema),controller.schedulePickup);
router.post("/:id/received",sensitiveRateLimit,validateParam("id"),requirePermission("orders.write"),validate(actionSchema),controller.receive);
router.post("/:id/replacement",sensitiveRateLimit,validateParam("id"),requirePermission("orders.write"),validate(actionSchema),controller.replacement);
router.post("/:id/refund",sensitiveRateLimit,validateParam("id"),requirePermission("payments.refund"),validate(actionSchema),controller.refund);
router.post("/:id/complete",sensitiveRateLimit,validateParam("id"),requirePermission("orders.write"),validate(actionSchema),controller.complete);
module.exports=router;
